const express = require('express');
const router = express.Router();
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage() });
const { body } = require('express-validator');
const { protect } = require('../middlewares/auth.middleware');
const { allow } = require('../middlewares/rbac.middleware');
const { validate } = require('../middlewares/validate.middleware');
const c = require('../controllers/admin.controller');
router.use(protect, allow('admin'));
router.get('/mentors', c.listMentors);
router.post('/mentors', c.createMentor);
router.patch('/mentors/:id', c.updateMentor);
router.post('/mentors/:id/deactivate', c.deactivateMentor);
router.delete('/mentors/:id', c.deleteMentor);
router.post('/mentors/bulk-upload', upload.single('file'), c.bulkUploadMentors);
router.get('/mentors/:mentorId/workload', c.getMentorWorkload);
router.get('/students', c.listStudents);
router.post('/students', c.createStudent);
router.patch('/students/:id', c.updateStudent);
router.post('/students/:id/deactivate', c.deactivateStudent);
router.delete('/students/:id', c.deleteStudent);
router.post('/students/bulk-upload', upload.single('file'), c.bulkUploadStudents);
router.post('/students/promote', c.promoteStudents);
router.get('/students/passout-batches', c.listPassoutBatches);
router.delete('/students/passout-batch', c.deletePassoutBatch);
router.get('/assignments', c.listAssignments);
router.post('/assignments/assign', c.assignStudents);
router.post('/assignments/unassign', c.unassignStudents);
router.get('/departments', c.listDepartments);
router.post('/departments', c.createDepartment);
router.patch('/departments/:id', c.updateDepartment);
router.get('/sessions', c.getAllSessions);
module.exports = router;