const express = require('express');
const router = express.Router();
const { body } = require('express-validator');
const { protect } = require('../middlewares/auth.middleware');
const { allow } = require('../middlewares/rbac.middleware');
const { validate } = require('../middlewares/validate.middleware');
const c = require('../controllers/student.controller');
router.use(protect, allow('student'));
router.get('/dashboard', c.getDashboard);
router.get('/mentor', c.getMyMentor);
router.get('/counseling-history', c.getMyCounselingHistory);
router.post('/concerns', [body('description').trim().notEmpty()], validate, c.submitConcern);
router.get('/concerns', c.getMyConcerns);
router.get('/messages', c.getConversation);
router.post('/messages', [body('content').trim().notEmpty()], validate, c.sendMessage);
router.get('/notifications', c.getNotifications);
router.patch('/notifications/:id/read', c.markNotificationRead);
module.exports = router;